<!--
This is for including Chapter 1. Notice that it's also good practice to name your chunk. This will help you debug potential issues as you knit. The chunk above is called intro and the one below is called chapter1. Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1. These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase. Look for the reference to this label at the beginning of Chapter 2.
-->

# État de l'art

## L'indice de fixation

En se différenciant génétiquement, les populations voient leurs fréquences d'allèles évoluer de façon indépendante. L'indice de fixation est une statistique permettant de quantifier pour un allèle donné, l'écart de la fréquence observée dans une sous-population à la fréquence théorique

## Modèle de FLK

Le modèle de FLK estime le modèle neutre d'un SNP bi-allélique lorsque celui-ci est uniquement soumis à la dérive génétique. À l'instant $t = 0$, le SNP a une fréquence $p_0$. Notant $F_t$ l'indice de fixation de cet allèle, $p(t)$ sa fréquence après $t$ générations, et en supposant que $F_t$ soit suffisamment petit, ce qui devrait être vérifié dans le cas neutre. [@nicholson2002assessing] : 

\begin{equation} 
  p(t) \sim N(p_0, F_t p_0 (1-p_0)) 
  (\#eq:frequency-law)
\end{equation}

De la loi \@ref(eq:frequency-law) nous tirons $\text{Var}(p(t)) = F_t p_0 (1-p_0)$.

La statistique FLK [@bonhomme2010detecting] requiert d'estimer au préalable deux paramètres que sont la fréquence allélique initiale $p_0$ et la matrice d'apparentement $V$, $V \in M_K(\mathbb{R})$ où $K$ est le nombre de populations observées. Notant : 

- $\boldsymbol{p} = (p_1, p_2, \dots, p_K) \in \mathbb{R}^K$, 

- $\boldsymbol{p_0} = (p_0, p_0, \dots, p_0) \in \mathbb{R}^K$, 

- $\boldsymbol{r} = N(0, V)$, 

le modèle neutre pour $\boldsymbol{p}$ est donné par la relation suivante : 

\begin{equation} 
  \boldsymbol{p} = \boldsymbol{p_0} + \boldsymbol{r} 
  (\#eq:flk-neutral-model)
\end{equation}

Bonhomme \textit{et al.} proposent pour ce modèle de mesurer une statistique de qualité de l'ajustement pour quantifier la déviance d'un allèle par rapport au modèle neutre : 

\begin{equation} 
  FLK = (\boldsymbol{p - \hat{p}_0})^T V (\boldsymbol{p - \hat{p}_0})                               
  (\#eq:flk-statistic)
\end{equation}

Sous l'hypothèse neutre et suivant \@ref(eq:flk-statistic), $FLK \sim \chi^2 (K - 1)$.

## Modèle de OutFLANK

En reprenant le modèle proposé par Lewontin et Krakauer [@lewontin1973distribution] et en y apportant les corrections nécessaires afin de prendre en compte les erreurs d'échantillonnage, 
Whitlock \textit{et al.} proposent une méthode permettant de détecter les allèles sous sélection en environnement hétérogène [@whitlock2015reliable]. Ainsi, la quantité 

\begin{equation} 
  k \frac{F_{ST}^{\prime}}{\bar{{F_{ST}^{\prime}}}}  
  (\#eq:OutFLANK-statistic)
\end{equation}

où $k$ représente le nombre de degrés de libertés.

## Modèle du logiciel Bayescan

Bayescan est aujourd'hui encore un des logiciels les plus utilisés pour détecter l'adaptation locale. Le modèle employé suppose que les sous-populations observées proviennent toutes d'une même population ancestrale. Pour une sous-population donnée et un SNP donné, la statistique de $F_{ST}$ peut être estimée en utilisant la
vraisemblance d’un modèle multinomial-Dirichlet [@beaumont2004identifying].
$F_{ST} \in [0, 1]$ est une quantité qui peut être interprété comme proportionnel à la probabilité que deux individus aient un ancêtre commun dans la sous-population

\begin{equation} 
  \log \left( \frac{F_{ST}}{1 - F_{ST}} \right) = \alpha_j + \beta_i + \gamma_{ij}
  (\#eq:Bayescan-statistic)
\end{equation}

## Fast PCA

### L'ACP en génétique des populations

L'utilisation de l'Analyse en Composantes Principales en génétique des populations a été popularisée par Cavalli-Sforza [@menozzi1978synthetic].

(ref:popres-cap) ACP réalisée sur le jeu de données POPRES [@novembre2008genes].

```{r popres, fig.cap = '(ref:popres-cap)'}
obj.popres <- readRDS("data/popres.rds")

ggdf <- data.frame(PC1 = -obj.popres$u[, 1], 
                   PC2 = -obj.popres$u[, 2],
                   pop = obj.popres$pop.fr)

ggplot(ggdf, aes(x = PC2, y = PC1, fill = pop)) + 
  geom_point(size = 2.5, shape = 21, stroke = 1) + 
  scale_fill_manual(labels = sort(unique(ggdf$pop)), 
                    values = as.character(obj.popres$palette.fr)) +
  guides(fill = guide_legend(nrow = 5)) +
  theme_bw() +
  theme(axis.text = element_text(face = "bold"),
        legend.text = element_text(size = 7.5),
        legend.key.height = unit(0.75, "line"),
        legend.key.width = unit(0.5, "line"),
        legend.title = element_blank(),
        legend.direction = "horizontal",
        legend.position = "bottom",
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm"))
```



## Analyse en Composantes Principales parcimonieuse

## Bootstrap ACP

## Contexte

## Tests multiples

## Contrôle du taux de fausse découverte

Le taux de fausse découverte, correspond à la proportion de faux positifs parmi les positifs. En notant $FP$ le nombre de faux positifs, $FP$ le nombre de vrais positifs, on définit le taux de fausse découverte $FDR$ par : 

\begin{equation} 
  FDR = \mathbb{E}\Big[\frac{FP}{TP + FP} 1_{FP+TP > 0}\Big] 
  (\#eq:FDR-def)
\end{equation}

- Référence cours de Christophe Giraud

q-value, bonferroni, benjamini-hochberg
La figure suivante donne les comparaisons entre les différentes procédures de correction :

